name: "corebuild"
froms: ["cr.ray.io/rayproject/oss-ci-base_build"]
dockerfile: ci/docker/core.build.Dockerfile
srcs:
  - python/requirements.txt
  - python/requirements_compiled.txt
  - python/requirements/test-requirements.txt
  - python/requirements/ml/dl-cpu-requirements.txt
  - python/requirements/nsight_fake/nsys_fake.py
  - python/requirements/nsight_fake/setup.py
tags:
  - cr.ray.io/rayproject/corebuild
